version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      tr:
        aliases:
          - frontend
    ports:
      - "8000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      tr:
        aliases:
          - backend
    ports:
      - "3001:3001"

  database:
    image: postgres:latest
    networks:
      tr:
        aliases:
          - database
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  tr:

volumes:
  db_data:
