version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
    networks:
      tr:
        aliases:
          - nginx
    volumes:
      - images_data:/var/www/data/images/
    ports:
      - "8080:80"
#       - "443:443"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      tr:
        aliases:
          - frontend
    ports:
      - "8000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - images_data:/uploads
    depends_on:
      - database
    networks:
      tr:
        aliases:
          - backend
    ports:
      - "3001:3001"

  database:
    image: postgres:latest
    networks:
      tr:
        aliases:
          - database
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./nginx/achievments.csv:/docker-entrypoint-initdb.d/achievments.csv
      - db_data:/var/lib/postgresql/data

networks:
  tr:

volumes:
  db_data:
    name: db_data
  images_data:
    name: images_data

