FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY cert.sh /etc/cert.sh

RUN apt-get update -yq && apt-get install certbot python3-certbot-nginx -yq && chmod +x /etc/cert.sh

CMD ["nginx", "-g", "daemon off;"]